---
- hosts: all
  vars:
    debspawn_git_url: "https://github.com/lkhq/debspawn.git"
  become: yes
  tasks:
    - apt: update_cache=yes upgrade=dist
    - apt: name=git
    - apt: name=xsltproc
    - apt: name=docbook-xsl
    - apt: name=python3-setuptools
    - apt: name=python3-pip
    - apt: name=python3-tomlkit
    - apt: name=python3-pkgconfig
    - apt: name=zstd
    - apt: name=systemd-container
    - apt: name=debootstrap

    - shell: dpkg-architecture -qDEB_BUILD_ARCH
      register: build_arch

    - name: Create buildd directory
      file:
        path: /srv/buildd
        state: directory

    # set up Laniakea DebSpawn Git repository
    - stat: path=/srv/buildd/debspawn-git
      register: debspawn_git

    - name: Update debspawn copy from git master
      shell: git fetch && git reset --hard origin/master
      args:
        chdir: /srv/buildd/debspawn-git
      when: debspawn_git.stat.exists == True

    - name: Clone debspawn from git master
      shell: git clone {{ debspawn_git_url }} debspawn-git
      args:
        chdir: /srv/buildd/
      when: debspawn_git.stat.exists == False

    - name: Install Debspawn 1/2
      shell: python3 setup.py install --root=/
      args:
        chdir: /srv/buildd/debspawn-git

    - name: Install Debspawn 2/2
      shell: python3 ./install-sysdata.py
      args:
        chdir: /srv/buildd/debspawn-git

    # a really, really ugly hack to ensure we have PureOS' debootstrap and keyring
    - name: "HACK: Install Debootstrap from untrusted local package"
      shell: wget {{ debootstrap_pkg_url }} -O debootstrap-new.deb && dpkg -i debootstrap-new.deb && rm debootstrap-new.deb
      args:
          chdir: /tmp
    - name: "HACK: Install Keyring from untrusted local package"
      shell: wget {{ keyring_pkg_url }} -O keyring.deb && dpkg -i keyring.deb && rm keyring.deb
      args:
          chdir: /tmp

    - name: Create new debspawn images
      shell: >
        debspawn create --arch={{ build_arch.stdout }}
        --components="main"
        --mirror={{ mirror }}
        --base-suite={{ item.value.base }}
        --extra-suites="{{ item.value.extra_suites | join(' ') }}"
        {{ item.key }}
      with_dict: "{{ suites }}"
      args:
        creates: /var/lib/debspawn/images/{{ item.key }}-buildd-{{ build_arch.stdout }}.tar.zst

    - name: Update debspawn images
      shell: >
        debspawn update --arch={{ build_arch.stdout }}
        {{ item.key }}
      with_dict: "{{ suites }}"

    # allow full /dev access to debspawn containers - this is really ugly, but needed to run vmdb2 in
    # a debspawn container, something which is made use of.
    - file: state=directory path=/etc/debspawn/
    - template: dest=/etc/debspawn/global.toml src=debspawn/global.toml.j2
